name: Flutter CI - Android Build on Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:

    runs-on: windows-latest

    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v3

    - name: 🧰 Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: stable

    - name: 📦 Install dependencies
      run: flutter pub get

    - name: 🧪 Run tests
      run: flutter test

    - name: 🔧 Enable Android build
      run: flutter config --enable-windows-desktop

    - name: 📦 Build APK (Debug)
      run: flutter build apk --debug

    - name: 📤 Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: debug-apk
        path: build/app/outputs/flutter-apk/app-debug.apk
